In [21]:
import numpy as np
import pandas as pd
import os

In [8]:
df = pd.read_csv("../data/rawdata/employee_attrition_dataset_10000.csv")
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

df.head()

   Employee_ID  Age  Gender Marital_Status Department   Job_Role  Job_Level  Monthly_Income  Hourly_Rate  Years_at_Company  Years_in_Current_Role  Years_Since_Last_Promotion  Work_Life_Balance  Job_Satisfaction  Performance_Rating  Training_Hours_Last_Year Overtime  Project_Count  Average_Hours_Worked_Per_Week  Absenteeism  Work_Environment_Satisfaction  Relationship_with_Manager  Job_Involvement  Distance_From_Home  Number_of_Companies_Worked Attrition
0            1   58    Male         Single    Finance    Manager          5            7332           81                24                     12                           3                  1                 3                   2                        74       No              9                             48           16                              4                          1                1                  49                           3        No
1            2   48  Female       Divorced         HR  Assistant          4            6069           55                18                      7                           5                  1                 2                   2                        24      Yes              9                             57           10                              4                          1                1                  25                           1        No
2            3   34  Female        Married  Marketing    Manager          4           11485           65                 6                      4                           3                  4                 5                   1                        63      Yes              3                             55            1                              1                          4                3                  21                           1       Yes
3            4   27  Female       Divorced         HR    Manager          4           18707           28                12                      9                           1                  1                 1                   2                         4       No              9                             53            2                              3                          4                1                  46                           2        No
4            5   40    Male        Married         HR    Analyst          1           16398           92                 3                      9                           1                  3                 4                   3                        62       No              1                             54           11                              1                          1                1                  43                           4        No

In [10]:
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nMissing values:", df.isnull().sum())
print("\nData types:", df.dtypes)
print("\nDuplicate rows:", df.duplicated().sum())

Shape: (10000, 26)

Columns: ['Employee_ID', 'Age', 'Gender', 'Marital_Status', 'Department', 'Job_Role', 'Job_Level', 'Monthly_Income', 'Hourly_Rate', 'Years_at_Company', 'Years_in_Current_Role', 'Years_Since_Last_Promotion', 'Work_Life_Balance', 'Job_Satisfaction', 'Performance_Rating', 'Training_Hours_Last_Year', 'Overtime', 'Project_Count', 'Average_Hours_Worked_Per_Week', 'Absenteeism', 'Work_Environment_Satisfaction', 'Relationship_with_Manager', 'Job_Involvement', 'Distance_From_Home', 'Number_of_Companies_Worked', 'Attrition']

Missing values: Employee_ID                      0
Age                              0
Gender                           0
Marital_Status                   0
Department                       0
Job_Role                         0
Job_Level                        0
Monthly_Income                   0
Hourly_Rate                      0
Years_at_Company                 0
Years_in_Current_Role            0
Years_Since_Last_Promotion       0
Work_Life_Balance                0
Job_Satisfaction                 0
Performance_Rating               0
Training_Hours_Last_Year         0
Overtime                         0
Project_Count                    0
Average_Hours_Worked_Per_Week    0
Absenteeism                      0
Work_Environment_Satisfaction    0
Relationship_with_Manager        0
Job_Involvement                  0
Distance_From_Home               0
Number_of_Companies_Worked       0
Attrition                        0
dtype: int64

Data types: Employee_ID                      int64
Age                              int64
Gender                             str
Marital_Status                     str
Department                         str
Job_Role                           str
Job_Level                        int64
Monthly_Income                   int64
Hourly_Rate                      int64
Years_at_Company                 int64
Years_in_Current_Role            int64
Years_Since_Last_Promotion       int64
Work_Life_Balance                int64
Job_Satisfaction                 int64
Performance_Rating               int64
Training_Hours_Last_Year         int64
Overtime                           str
Project_Count                    int64
Average_Hours_Worked_Per_Week    int64
Absenteeism                      int64
Work_Environment_Satisfaction    int64
Relationship_with_Manager        int64
Job_Involvement                  int64
Distance_From_Home               int64
Number_of_Companies_Worked       int64
Attrition                          str
dtype: object

Duplicate rows: 0

In [11]:
retainx_df = df.sample(
    n=1000,
    random_state=42
).reset_index(drop=True)

print("RetainX Dataset Created!")
print("Shape:", retainx_df.shape)

RetainX Dataset Created!
Shape: (1000, 26)

In [13]:
output_directory = "../data/processed"
os.makedirs(output_directory, exist_ok=True)
output_path="../data/processed/retainx_hr_1000.csv"
retainx_df.to_csv(output_path, index=False)
print("Dataset saved successfully!", output_path)

Dataset saved successfully! ../data/processed/retainx_hr_1000.csv

In [14]:
print(retainx_df.shape)

(1000, 26)

In [15]:
retainx_df.head(10)

   Employee_ID  Age  Gender Marital_Status Department   Job_Role  Job_Level  Monthly_Income  Hourly_Rate  Years_at_Company  Years_in_Current_Role  Years_Since_Last_Promotion  Work_Life_Balance  Job_Satisfaction  Performance_Rating  Training_Hours_Last_Year Overtime  Project_Count  Average_Hours_Worked_Per_Week  Absenteeism  Work_Environment_Satisfaction  Relationship_with_Manager  Job_Involvement  Distance_From_Home  Number_of_Companies_Worked Attrition
0         6253   31    Male       Divorced  Marketing  Assistant          3           13410           89                 9                      9                           0                  1                 5                   1                        24      Yes              9                             32           18                              4                          3                1                  34                           4        No
1         4685   25    Male       Divorced         HR    Analyst          3           11034           66                12                     10                           5                  1                 4                   4                         9       No              2                             58           18                              1                          4                1                  23                           1       Yes
2         1732   50  Female       Divorced         IT  Assistant          5           18595           56                24                      9                           4                  3                 4                   1                        18      Yes              2                             42            4                              4                          4                4                  39                           3       Yes
3         4743   36    Male       Divorced      Sales  Executive          4           13160           65                17                      4                           4                  1                 3                   3                        28      Yes              1                             41            3                              4                          4                4                  39                           4       Yes
4         4522   43  Female        Married    Finance    Analyst          5           14131           44                16                     10                           5                  3                 1                   1                        30       No              7                             48            5                              2                          1                1                   1                           4       Yes
5         6341   59  Female        Married    Finance  Assistant          5           11820           69                22                      1                           2                  4                 2                   4                        56       No              4                             44           15                              3                          1                4                   2                           3        No
6          577   54  Female        Married      Sales  Assistant          3            9720           54                13                      1                           7                  1                 1                   1                        95      Yes              8                             30           15                              2                          3                2                   9                           3        No
7         5203   27  Female        Married         IT    Analyst          4           14399           84                 6                     13                           3                  1                 1                   3                        56       No              2                             55           10                              1                          3                1                  37                           1       Yes
8         6364   45    Male        Married         IT  Executive          2            3688           74                21                     11                           4                  3                 3                   4                        65      Yes              1                             46            5                              2                          2                4                  18                           1        No
9          440   20  Female        Married         HR  Executive          1            4656           43                21                      9                           1                  3                 2                   4                        20       No              1                             58            8                              3                          1                2                  23                           2        No

In [16]:
print(retainx_df["Attrition"].value_counts())

Attrition
No     788
Yes    212
Name: count, dtype: int64

In [ ]:
# Attrition = "Yes": The employee has left the company (resigned, terminated, or retired).
# Attrition = "No": The employee is active and currently still working in the organization.

In [18]:
# Employees Attrition rate :
# Employees who left
# ──────────────────── × 100
# Total employees

In [20]:
totalemp=len(retainx_df)
attrition_count=(retainx_df["Attrition"]=="Yes").sum()
active_count=(retainx_df["Attrition"]=="No").sum()

attrition_rate=(attrition_count/totalemp)*100

print(f"Total employees : {totalemp}")
print(f"Active employees : {active_count}")
print(f"Attrition employees : {attrition_count}")
print(f"Overall Attrition rate : {attrition_rate:.2f}%")

Total employees : 1000
Active employees : 788
Attrition employees : 212
Overall Attrition rate : 21.20%

In [23]:
retainx_df.head()

   Employee_ID  Age  Gender Marital_Status Department   Job_Role  Job_Level  Monthly_Income  Hourly_Rate  Years_at_Company  Years_in_Current_Role  Years_Since_Last_Promotion  Work_Life_Balance  Job_Satisfaction  Performance_Rating  Training_Hours_Last_Year Overtime  Project_Count  Average_Hours_Worked_Per_Week  Absenteeism  Work_Environment_Satisfaction  Relationship_with_Manager  Job_Involvement  Distance_From_Home  Number_of_Companies_Worked Attrition
0         6253   31    Male       Divorced  Marketing  Assistant          3           13410           89                 9                      9                           0                  1                 5                   1                        24      Yes              9                             32           18                              4                          3                1                  34                           4        No
1         4685   25    Male       Divorced         HR    Analyst          3           11034           66                12                     10                           5                  1                 4                   4                         9       No              2                             58           18                              1                          4                1                  23                           1       Yes
2         1732   50  Female       Divorced         IT  Assistant          5           18595           56                24                      9                           4                  3                 4                   1                        18      Yes              2                             42            4                              4                          4                4                  39                           3       Yes
3         4743   36    Male       Divorced      Sales  Executive          4           13160           65                17                      4                           4                  1                 3                   3                        28      Yes              1                             41            3                              4                          4                4                  39                           4       Yes
4         4522   43  Female        Married    Finance    Analyst          5           14131           44                16                     10                           5                  3                 1                   1                        30       No              7                             48            5                              2                          1                1                   1                           4       Yes

In [24]:
rating_columns = [
    "Job_Level",
    "Work_Life_Balance",
    "Job_Satisfaction",
    "Performance_Rating",
    "Work_Environment_Satisfaction",
    "Relationship_with_Manager",
    "Job_Involvement"
]

for column in rating_columns:
    print(f"{column}: {sorted(retainx_df[column].unique())}")

Job_Level: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Work_Life_Balance: [np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
Job_Satisfaction: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Performance_Rating: [np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
Work_Environment_Satisfaction: [np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
Relationship_with_Manager: [np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
Job_Involvement: [np.int64(1), np.int64(2), np.int64(3), np.int64(4)]